In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
X = df.drop('sales', axis = 1)

In [4]:
y = df['sales']

In [6]:
from sklearn.preprocessing import  PolynomialFeatures

In [7]:
polynomial_converter = PolynomialFeatures(degree = 3, include_bias = False)

In [8]:
poly_features = polynomial_converter.fit_transform(X)

In [9]:
X.shape

(200, 3)

In [10]:
poly_features.shape

(200, 19)

In [12]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, 
                                                    random_state=101)

In [15]:
X_train.shape

(140, 19)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()

In [18]:
scaler.fit(X_train)

StandardScaler()

In [19]:
X_train = scaler.transform(X_train)

In [20]:
X_test = scaler.transform(X_test)

In [21]:
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]])

In [23]:
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [24]:
from sklearn.linear_model import Ridge

In [25]:
help(Ridge)

Help on class Ridge in module sklearn.linear_model._ridge:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(alpha=1.0, *, fit_intercept=True, copy_X=True, max_iter=None, tol=0.0001, solver='auto', positive=False, random_state=None)
 |  
 |  Linear least squares with l2 regularization.
 |  
 |  Minimizes the objective function::
 |  
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |  
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.0
 |      Constant that multiplies the L2 term, controlling regula

In [26]:
ridge_model = Ridge(alpha = 10)

In [28]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [29]:
test_predictions = ridge_model.predict(X_test)

In [30]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [31]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.5774404204714175

In [33]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.8946386461319681

In [34]:
from sklearn.linear_model import RidgeCV

In [42]:
ridge_cv_model = RidgeCV(alphas = (0.1, 1, 10), scoring = 'neg_mean_absolute_error')

In [43]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=(0.1, 1, 10), scoring='neg_mean_absolute_error')

In [44]:
ridge_cv_model.alpha_

0.1

In [45]:
test_predictions = ridge_cv_model.predict(X_test)

In [46]:
MAE = mean_absolute_error(y_test, test_predictions)

In [47]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [48]:
MAE

0.42737748843675194

In [49]:
RMSE

0.6180719926956963

In [50]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [51]:
ridge_cv_model.best_score_

-0.3749223340292957

# LASSO - least absolute shrinkage and selection operator

In [53]:
from sklearn.linear_model import LassoCV

In [58]:
lasso_cv_model = LassoCV(eps = 0.1, n_alphas = 100, cv = 5)

In [59]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [60]:
lasso_cv_model.alpha_

0.4943070909225828

In [61]:
test_predictions = lasso_cv_model.predict(X_test)

In [64]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.6541723161252856

In [65]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

1.1308001022762535

In [66]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [67]:
from sklearn.linear_model import ElasticNetCV

In [68]:
elastic_model = ElasticNetCV(l1_ratio = [.1, .5, .7, .9, .95, .99, 1], eps = 0.001, n_alphas = 100, max_iter = 1000000)

In [69]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [70]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [72]:
elastic_model.l1_ratio_

1.0

In [73]:
elastic_model.alpha_

0.004943070909225827

In [74]:
lasso_cv_model.alpha_

0.4943070909225828

In [75]:
test_predictions = elastic_model.predict(X_test)

In [76]:
MAE = mean_absolute_error(y_test, test_predictions)

In [77]:
MAE

0.4335034618590069